### PR TITLE
Update DigiBruteDroid.ino

### PR DESCRIPTION
**Pull request by s7560m**
Added for loops instead of multiple ifs. Makes code much easier to read.

### CODE REVIEW

**Comment by seattleandrew** [comment]
While yes the for loops are cleaner, it breaks the purpose of the loop() function. The program is supposed to iterate through the loop multiple times. If you add a for loop, it won't actually help since you'll be iterating over 10,000 possibilities without actually doing anything.

**Comment by s7560m** [comment]
Actually I made a mistake in my code, but I appreciate you getting back. I meant to for loop with the variables initiating at 0, and condition it when it equals 9. It is iterating over 10000 possibilities whilst doing something, and that something is the function of this code. It's essentially the same as the multiple if conditions stated in there, except that instead it is being replaced with for loops. 

Edit: I fixed my commit to the things mentioned. Remember that the variables mentioned in the for loops are the exact variables that you've declared, not a brand new declaration of ints.

**Comment by seattleandrew** [comment]
Sorry for the late delay, in order to properly merge the code, inside each of the for loops you'll need to add functions to send keystrokes to the Android device. The purpose is to iterate over all the combinations a 4 digit PIN could be and send those codes as keyboard interactions to the device. I'll gladly accept the pull if you can implement those keystrokes.

**Comment by s7560m** [comment]
Ah, true, I get what you're saying. I'll see to modifying my pull to hopefully add new things, like your todo. And no problem for the late response. I was worried that you were ignoring for a bit, but it's not much of a big deal. I'll dismiss the for loops for sure.

**Comment by seattleandrew** [comment]
I actually liked your idea of for loops :-/ It is indeed much cleaner. I think we need to consider a rewrite for the code to recursively loop through digits. I'll try whiteboarding an idea later this week when I'm back from my business trip.

**Comment by s7560m** [comment]
Of course, that sounds like a good idea.

**Pull request closed without merging**
